language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
      - python-pip
      - python-scipy
install:
  python setup.py install
script:
  python setup.py test
